---
title: "trytry"
author: "Saier Gong (sg3772)"
date: "4/18/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,warning = FALSE,error = FALSE)
```

### Step 1 Load Data and Train-test Split
```{r}
library(dplyr)
library(tidyr)
library(ggplot2)
library(lubridate)
data <- read.csv("../data/ml-latest-small/ratings.csv") %>%
  mutate(Date=as.Date(as.POSIXct(timestamp,origin="1970-01-01",tz='UTC')))

source(file = "data_split(need modify).R")

#set.seed(0)
#test_idx <- sample(1:nrow(data), round(nrow(data)/5, 0))
#train_idx <- setdiff(1:nrow(data), test_idx)

set.seed(0)
split<-train_test_split(data = data,train_ratio = 0.8)
data_train <- split$train
data_test <- split$test
```

###Step 2 Matrix Factorization
```{r}
###some preparation



RMSE<-function(rating,est_rating){
  a<-sqrt(mean((rating-est_rating)^2))
  return(a)
}

```


```{r}
##tu is the data frame of the mean date of rating of each user in 'data' dataset.
als.td<-function(f=10,lambda=0.1,max.iter=5,data,data_train,data_test){
  data<-data %>%
    arrange(userId,movieId)
  
  tu<-data %>%
    group_by(userId) %>%
    summarise(meanDate=round_date(mean(Date),'day'))

beta<-0.4




train<-data_train %>%
  arrange(userId,movieId) %>%
  mutate(diff=as.numeric(Date-tu$meanDate[userId])) %>%
  mutate(dev=sign(diff)*(as.numeric( abs(diff)^beta)) ) ### train dataset contains all the parameters needed for calculation

mu<-mean(train$rating)

#train1<-train %>%
#  mutate(rating=rating-mu)

test<-data_test %>%
  arrange(userId,movieId) %>%
  mutate(diff=as.numeric(Date-tu$meanDate[userId])) %>%
  mutate(dev=sign(diff)*(as.numeric(abs(diff)))^beta)

U<-length(unique(data$userId)) #the number of all users
I<-length(unique(data$movieId)) # the number of all movies

#initialize q
guodu<-data %>%
  group_by(movieId) %>%
  summarise(row_1=mean(rating-mu))


#q<- rbind(guodu$row_1,matrix(data=runif((f-1)*I,min = -1,max = 1),nrow = f-1,ncol = I))
set.seed(0)
q<-matrix(data=runif(f*I,-1,1),nrow = f,ncol = I)
colnames(q)<-as.character(sort(unique(data$movieId)))#movie feature matrix

#initialize bu
bu<-rep(0,U)
names(bu)<-as.character(sort(unique(data$userId)))

#initialize alpha.u
alpha.u<-rep(0,U)
names(alpha.u)<-as.character(sort(unique(data$userId)))

#initialize bi
#b<-train %>%
#  group_by(movieId) %>%
#  summarise(meanMovie=mean(rating))
#bi<-b$meanMovie-mu

set.seed(0)
bi<-runif(I,-0.5,0.5)
names(bi)<-as.character(sort(unique(data$movieId)))


#set.seed(0)
p<-matrix(nrow = f,ncol = U)
colnames(p)<-as.character(sort(unique(train$userId)))#user feature matrix

train.rmse<-c()
test.rmse<-c()




for (l in 1:max.iter) {
 
  
       ####update p
  for (u in 1:U) {
    #the movie user u rated
    I.u<-train %>%
      filter(userId==u)
    
    q.I.u<-q[,as.character(I.u$movieId)] #the movie feature u has rated
    R.u<-I.u$rating
    
    A<-q.I.u %*% t(q.I.u)+lambda * nrow(I.u) *diag(f)
    V<-q.I.u %*% (R.u-bu[as.character(I.u$userId)]-bi[as.character(I.u$movieId)]-mu-alpha.u[as.character(I.u$userId)]*I.u$dev)
    
    p[,u]<-solve(A,tol = 1e-50) %*% V
    
    
  }
  
    ###update bi
  #for (m in 1:I) {
  #  U.m<-train %>%
  #    filter(movieId==as.numeric(names(bi)[m]))
  #  
  #  
  # pred.R.m<-c()
  # for (j in 1:nrow(U.m)) {
  #   
  #   pred.R.m[j]<-as.numeric(t(q[,m]) %*% p[,U.m$userId[j] ]    )
  #   
  #   
  # }
  # 
  # ###new bi
  # bi[m]<-(sum(U.m$rating)-sum(pred.R.m)-sum(bu)-nrow(U.m)*mu-sum(alpha.u[U.m$userId]*U.m$dev)  )/(nrow(U.m)+lambda)
  # 
  # 
  #  
  #}
  
  
  
  
   ###update alpha.u
  
  for (u in 1:U) {
    I.u<-train %>%
      filter(userId==u)
    
    
    pred.R.u<-c()
    for (i in 1:nrow(I.u)) {
      pred.R.u[i]<- as.numeric(t(p[,u]) %*% q[,as.character(I.u$movieId[i])]) #+mu+ bu[as.character(u)]+
        #bi[as.character(I.u$movieId[i])]+ alpha.u[as.character(u)] * I.u$dev[i]

    }
    
    
    ##new alpha.u
    alpha.u[u]<-(sum(I.u$rating*I.u$dev)-sum(bi[as.character(I.u$movieId[i])]*I.u$dev)-sum(mu*I.u$dev)
                          - sum(pred.R.u*I.u$dev))/(sum(I.u$dev^2)+lambda)
      
  }
  
  
  
  
  
  
  ###update bu
  for (u in 1:U) {
    I.u<-train %>%
      filter(userId==u)
    
    
    pred.R.u<-c()
    #calculate predict rating of user u
    for (i in 1:nrow(I.u)) {
      pred.R.u[i]<- as.numeric(t(p[,u]) %*% q[,as.character(I.u$movieId[i])])
      
    }
    
    
    ##new bu
    bu[u]<-(sum(I.u$rating) - sum(pred.R.u)-sum(bi)-nrow(I.u)*mu-sum(alpha.u[u]*I.u$dev))/(nrow(I.u)+lambda)
    
  }
  
  
 

  
  

  
 
 
  
  
  
  ###update q movie feature
  
  for (m in 1:I) {
    U.m<-train %>%
      filter(movieId==as.numeric(names(bi)[m]))
    
    
    p.U.m<-p[,U.m$userId] #the user feature who has rated movie m
    R.m<-U.m$rating
    
    A<-p.U.m %*% t(p.U.m)+lambda * nrow(U.m) *diag(f)
    V<-p.U.m %*% as.matrix(R.m-bu[U.m$userId]-bi[as.character(U.m$movieId)]-mu-alpha.u[U.m$userId]*U.m$dev)
    
    q[,m]<-solve(A,tol = 1e-50) %*% V
   
   
    
  }
  
  R_hat<-as.data.frame(t(p) %*% q)
 
  R_hat<-R_hat %>%
    mutate(userId=as.numeric(names(bu))) %>%
    pivot_longer(cols = names(bi)[1]:names(bi)[length(bi)],
                 names_to = "movieId",
                 values_to = "est2") %>%
    mutate(movieId=as.numeric(movieId))
  
  
  
  train.with.est<-train %>%
    mutate(est1=mu+bi[as.character(movieId)]+bu[userId]+alpha.u[userId]*dev) %>%
    left_join(R_hat) %>%
    mutate(est_rating=est1+est2)
  
  train.result<-RMSE(train$rating,train.with.est$est_rating)
  train.rmse[l]<-train.result
  
  
  
  test.with.est<-test %>%
    mutate(est1=mu+bi[as.character(movieId)]+bu[as.character(userId)]+alpha.u[as.character(userId)]*dev) %>%
    left_join(R_hat) %>%
    mutate(est_rating=est1+est2) %>%
    filter(!is.na(est_rating))
    
  test.result<-RMSE(test.with.est$rating,test.with.est$est_rating)
  test.rmse[l]<-test.result
  
}#wai ceng da xun huan de kuo hao

result.tibble<-tibble(train_rmse=train.rmse,
                      test_rmse=test.rmse)

return(r=list(p=p,q=q,mu=mu,bu=bu,bi=bi,alpha.u=alpha.u,rmse=result.tibble))
}


r0<-als.td(f=10,lambda = 0.1,max.iter = 5,data,data_train,data_test)

```





```{r}
r0$rmse

```


```{r}
####cross validation
cv.function <- function(data_train, K, f, lambda){
  ### Input:
  ### - train data frame
  ### - K: a number stands for K-fold CV
  ### - tuning parameters 
  
  n <- dim(data_train)[1]
  n.fold <- round(n/K, 0)
  
  
  train_rmse <- matrix( 0,ncol = 5,nrow = K) #### 5=max.iter
  test_rmse <- matrix( 0,ncol = 5, nrow = K)
  
  for (i in 1:K){
    train.data <- train_test_split(data = data_train,train_ratio=(1-1/K))$train
    test.data <- train_test_split(data = data_train,train_ratio =(1-1/K))$test
    
    result <- als.td(f=f,lambda=lambda,max.iter = 5,data = data_train,data_train = train.data,data_test = test.data)
  
    train_rmse[i,] <-  (result$rmse)$train_rmse
    test_rmse[i,] <-   (result$rmse)$test_rmse
    
  }		
  return(list(mean_train_rmse = colMeans(train_rmse), mean_test_rmse = colMeans(test_rmse)))
         #sd_train_rmse = apply(train_rmse, 2, sd), sd_test_rmse = apply(test_rmse, 2, sd)))
}

f_list <- seq(10, 20, 10)
l_list <- seq(-2, -1, 1)
f_l <- expand.grid(f_list, l_list)
K=5

train_summary<-matrix(0,nrow = 5,ncol = 4)
test_summary<-matrix(0,nrow = 5,ncol = 4)
for(i in 1:nrow(f_l)){
    par <- paste("f = ", f_l[i,1], ", lambda = ", 10^f_l[i,2])
    cat(par, "\n")
    current_result <- cv.function(data_train=data_train, K = 5, f = f_l[i,1], lambda = 10^f_l[i,2])
    train_summary[,i]<-current_result$mean_train_rmse
    test_summary[,i]<-current_result$mean_test_rmse
    
    #print(train_summary)
    #print(test_summary)
  
}

print(train_summary)
print(test_summary)

```

So we choose $f=20,\lambda=0.01$.


```{r}

save(train_summary,file = "train_summary.RData")

save(test_summary,file = "test_summary.RData")
```


# KNN
```{r}
r<-als.td(f=20,lambda=0.01,max.iter = 5,data = data,data_train = data_train,data_test = data_test)

save(r,file = "optimize_rmse_and_parameters.RData")
load("optimize_rmse_and_parameters.RData")

```



```{r}
#source(file = "knn.R")


d<-function(x){
  s<-sum(x^2)
  return(sqrt(s))
}



where.max<-function(x){
  location<-which.max(x)
  return(as.numeric(names(x)[location]))
}

length<-apply(q, 2, d)
names(length)<-colnames(q)


pred.knn<-function(data_train,data_test,q){
  
  ##similarity matrix betwee movies

  
 
  predict.knn<-c()
  
  ###knn
  for (m in 1:nrow(data_test)) {
    user<-data_test$userId[m]
    movie<-data_test$movieId[m]
    q.movie<-q[,colnames(q)==as.character(movie)]
    
    
    train<-data_train %>%
      filter(userId==user)
    
    train.movie<-train$movieId
    
    s<-as.numeric(t(q.movie) %*% q[,colnames(q) %in% as.character(train.movie)])
    similar<-s/(length[as.character(movie)] * length[as.character(train.movie)])
    
    close.movie<-where.max(similar)
    
    predict.knn[m]<-as.double(train %>%
      filter(movieId==close.movie) %>%
      select(rating))
  
    
  }
  
 
  rmse<-RMSE(data_test$rating,predict.knn)
  
  return(list(knn=predict.knn,rmse=rmse))
  
}


answer<-pred.knn(data_train,data_test,q=r$q)

save(answer,file = "answer.RData")
```